version: 0.2

phases:
  build:
    commands:
      - >-
        ECS_TASK_DEFINITION=$(aws ecs describe-services
        --service $ECS_SERVICE
        --cluster $ECS_CLUSTER
        --query "reverse(sort_by(services, &createdAt))[0].taskDefinition"
        --output text)
      - echo $ECS_TASK_DEFINITION

      - DATABASE_CONNECTION=${DATABASE_CONNECTION:-default}
      - echo $DATABASE_CONNECTION

      - >-
        RUN_RESULT=$(aws ecs run-task --region ap-southeast-1 --started-by "migration"
        --cluster $ECS_CLUSTER
        --task-definition $ECS_TASK_DEFINITION
        --overrides '{"containerOverrides":[{"name": "'${ECS_CONTAINERNAME}'", "command": ["/bin/sh", "-c", "python manage.py migrate --database '${DATABASE_CONNECTION}'"]}], "cpu": "1024", "memory": "2GB"}'
        --launch-type FARGATE
        --network-configuration "awsvpcConfiguration={subnets=[${SUBNET}],securityGroups=[${SG}],assignPublicIp=DISABLED"})

      - echo $RUN_RESULT
