# Generated by Django 5.1 on 2024-11-12 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineIntegration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("line_chatbot_api_key", models.CharField(max_length=255)),
                ("line_channel_secret", models.CharField(max_length=255)),
            ],
        ),
    ]
