# Generated by Django 5.1 on 2024-11-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_center", "0003_alter_organizationmember_organization_and_more"),
        ("webhook_line", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineintegration",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat_center.organization",
            ),
        ),
    ]
