# Generated by Django 5.1.3 on 2024-12-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_line', '0002_lineintegration_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=255)),
                ('routing', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('HR', 'Hr')], max_length=100)),
                ('retrieve_image', models.BooleanField(blank=True, null=True)),
                ('knowledge_base', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration')),
            ],
        ),
    ]
