# Generated by Django 5.1.3 on 2025-01-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0008_routingchain'),
        ('webhook_line', '0003_routingchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.routingchain')),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration')),
            ],
        ),
        migrations.DeleteModel(
            name='RoutingChain',
        ),
    ]
