# Generated by Django 5.1.4 on 2025-02-06 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0027_fieldconnection_routingskill_and_more'),
        ('webhook_line', '0004_lineconnection_delete_routingchain'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineConnectionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.routingchain')),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration')),
            ],
        ),
    ]
