# Generated by Django 5.1.4 on 2025-02-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_line', '0005_lineconnectionnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineConnection',
        ),
    ]
