# Generated by Django 5.1.3 on 2025-02-18 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_line', '0006_delete_lineconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineintegration',
            name='connected_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
