# Generated by Django 5.1 on 2024-11-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "platform_id",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("img", models.CharField(blank=True, max_length=1000, null=True)),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
                ("tag", models.CharField(blank=True, max_length=1000, null=True)),
                ("priority", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "lastest_msg",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=1000, null=True)),
                ("agent", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "message_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reply_token",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("by", models.CharField(blank=True, max_length=1000, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "platform_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_center.user",
                    ),
                ),
            ],
        ),
    ]
