# Generated by Django 5.1 on 2024-08-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LINE', 'Line'), ('FACEBOOK', 'Facebook')])),
                ('platform_uid', models.TextField()),
                ('platform_name', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('latest_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='chat_center.customer')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='chat_center.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_from_customer', models.BooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat_center.case')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('auto_escalate', models.DurationField(blank=True, null=True)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handlers', to='chat_center.topic')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='topic_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='chat_center.topichandler'),
        ),
        migrations.AddConstraint(
            model_name='topichandler',
            constraint=models.UniqueConstraint(fields=('topic', 'index'), name='topic_handler'),
        ),
    ]
