# Generated by Django 5.1 on 2024-12-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_center", "0005_alter_message_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
                ("gender", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "phonenumber",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("citizenid", models.CharField(blank=True, max_length=1000, null=True)),
                ("birthday", models.CharField(blank=True, max_length=1000, null=True)),
                ("email", models.CharField(blank=True, max_length=1000, null=True)),
                ("satisfaction", models.IntegerField(blank=True, null=True)),
                ("dissatisfaction", models.IntegerField(blank=True, null=True)),
                ("totalsession", models.IntegerField(blank=True, null=True)),
                ("totalmessage", models.IntegerField(blank=True, null=True)),
                ("urgent", models.IntegerField(blank=True, null=True)),
                ("priority", models.CharField(blank=True, max_length=1000, null=True)),
                ("intentsummary", models.TextField(blank=True, null=True)),
                (
                    "platform_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_center.customer",
                    ),
                ),
            ],
        ),
    ]
