# Generated by Django 5.1.3 on 2025-01-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0007_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingChain',
            fields=[
                ('bot_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(max_length=255)),
                ('routing', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('HR', 'Hr')], max_length=100)),
                ('retrieve_image', models.BooleanField(blank=True, null=True)),
                ('knowledge_base', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
