# Generated by Django 5.1.4 on 2025-01-06 07:42

import apps.chat_center.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0007_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='organization_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.organizationmember'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=apps.chat_center.models.file_upload_to),
        ),
    ]
