# Generated by Django 5.1 on 2025-01-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_center", "0008_uploadedfile_organization_member_and_more"),
        ("chat_center", "0009_routingchain_is_active"),
    ]

    operations = []
