# Generated by Django 5.1.3 on 2025-01-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0010_merge_20250106_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingchain',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='organization_member',
        ),
        migrations.AddField(
            model_name='routingchain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
