# Generated by Django 5.1.4 on 2025-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0012_uploadedfile_organization_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='collection_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='embedded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
