# Generated by Django 5.1.4 on 2025-01-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0013_uploadedfile_collection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSummarize',
            fields=[
                ('platform_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('summarize', models.TextField(blank=True, null=True)),
                ('latest_msg_date', models.DateTimeField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserSatisfaction',
            fields=[
                ('platform_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('latest_msg_date', models.DateTimeField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserUrgent',
            fields=[
                ('platform_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('urgent', models.IntegerField(blank=True, null=True)),
                ('latest_msg_date', models.DateTimeField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
