# Generated by Django 5.1.4 on 2025-01-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0014_chatsummarize_chatusersatisfaction_chatuserurgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsummarize',
            old_name='latest_msg_date',
            new_name='lastest_msg_date',
        ),
        migrations.RenameField(
            model_name='chatusersatisfaction',
            old_name='latest_msg_date',
            new_name='lastest_msg_date',
        ),
        migrations.RenameField(
            model_name='chatuserurgent',
            old_name='latest_msg_date',
            new_name='lastest_msg_date',
        ),
    ]
