# Generated by Django 5.1.4 on 2025-01-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0019_rename_by_internalchatsession_session_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalchatsession',
            name='bot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.routingchain'),
        ),
    ]
