# Generated by Django 5.1.4 on 2025-01-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0020_internalchatsession_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
    ]
