# Generated by Django 5.1.4 on 2025-01-28 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0021_alter_uploadedfile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalchatsession',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalchatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routingchain',
            name='industry',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('HR', 'Hr'), ('RETAIL', 'Retail')], max_length=100),
        ),
    ]
