# Generated by Django 5.1.4 on 2025-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0022_internalchatsession_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
