# Generated by Django 5.1.4 on 2025-01-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0023_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
