# Generated by Django 5.1.4 on 2025-02-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0024_uploadedfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingchain',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_center.organization'),
        ),
    ]
