# Generated by Django 5.1.4 on 2025-02-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0025_routingchain_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_center.organization'),
        ),
    ]
