# Generated by Django 5.1.3 on 2025-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0029_customer_from_line_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingchain',
            name='knowledge_base_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
