# Generated by Django 5.1.4 on 2025-03-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0030_routingchain_knowledge_base_list'),
        ('webhook_line', '0008_lineintegration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_line_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration'),
        ),
    ]
