# Generated by Django 5.1.4 on 2025-03-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0031_message_from_line_uuid'),
        ('webhook_line', '0008_lineintegration_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=1000)),
                ('img', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastest_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=1000, null=True)),
                ('agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('message_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('from_line_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration')),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_center.organization')),
            ],
            options={
                'unique_together': {('platform_id', 'from_line_uuid')},
            },
        ),
    ]
