# Generated by Django 5.1.7 on 2025-03-12 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0032_customernew'),
        ('webhook_line', '0008_lineintegration_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('citizenid', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('dissatisfaction', models.IntegerField(blank=True, null=True)),
                ('totalsession', models.IntegerField(blank=True, null=True)),
                ('totalmessage', models.IntegerField(blank=True, null=True)),
                ('urgent', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=1000, null=True)),
                ('intentsummary', models.TextField(blank=True, null=True)),
                ('platform_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.customernew')),
            ],
        ),
        migrations.CreateModel(
            name='MessageNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('from_line_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_line.lineintegration')),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_center.organization')),
                ('platform_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_center.customernew')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
