# Generated by Django 5.1.3 on 2025-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0033_dashboardnew_messagenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingchain',
            name='is_publish',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
