# Generated by Django 5.2 on 2025-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_center', '0035_informationextractionskillnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingchain',
            name='industry',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('HR', 'Hr'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
